<?php
defined('BASEPATH') OR exit('No direct script access allowed');
?>
<div id="container">
    <h1>Welcome to COBORFF!</h1>

    <p>This page was generated by codeigniter under the Welcome controller!</p>
    <p class="well">This is a well, just to show you how bootstrap is working!</p>
    <p>Here is a Font Awesome icon for you: <i class="fa fa-heart"></i></p>

    <?php
    if ($fb_user) {
        echo "<p>You have a facebook user logged in!</p>";
        print_r($fb_user);
    } else {
        ?>
        <p><a href="<?= $login_url; ?>">Login with Facebook</a></p>
    <?php } ?>

    <p class="footer">Page rendered in <strong>{elapsed_time}</strong> seconds. <?php echo (ENVIRONMENT === 'development') ? 'CodeIgniter Version <strong>' . CI_VERSION . '</strong>' : '' ?></p>
</div>